//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : DrugDB
	/// Data Source    : E:\TEMP\DrugDB.mdb
	/// Server Version : 04.00.0000
	/// </summary>
	public partial class DrugDBDB : LinqToDB.Data.DataConnection
	{
		public ITable<BenhNhan>    BenhNhans     { get { return this.GetTable<BenhNhan>(); } }
		public ITable<Drug>        Drugs         { get { return this.GetTable<Drug>(); } }
		public ITable<DrugHistory> DrugHistories { get { return this.GetTable<DrugHistory>(); } }

		public DrugDBDB()
		{
			InitDataContext();
		}

		public DrugDBDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("BenhNhan")]
	public partial class BenhNhan
	{
		[PrimaryKey, Identity] public int       ID       { get; set; } // Long
		[Column,     Nullable] public string    Name     { get; set; } // text(255)
		[Column,     Nullable] public string    Phone    { get; set; } // text(255)
		[Column,     Nullable] public DateTime? BirthDay { get; set; } // DateTime
	}

	[Table("Drug")]
	public partial class Drug
	{
		[PrimaryKey, Identity] public int    ID   { get; set; } // Long
		[Column,     Nullable] public string Name { get; set; } // text(255)
	}

	[Table("DrugHistory")]
	public partial class DrugHistory
	{
		[PrimaryKey, Identity   ] public int       ID         { get; set; } // Long
		[            Identity   ] public int       BenhNhanID { get; set; } // Long
		[Column,     NotNull    ] public string    DrugName   { get; set; } // text(255)
		[Column,     NotNull    ] public string    Unit       { get; set; } // text(255)
		[            Identity   ] public int       Count      { get; set; } // Long
		[            Identity   ] public int       Price      { get; set; } // Long
		[Column,        Nullable] public DateTime? Date       { get; set; } // DateTime
	}

	public static partial class TableExtensions
	{
		public static BenhNhan Find(this ITable<BenhNhan> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static Drug Find(this ITable<Drug> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}

		public static DrugHistory Find(this ITable<DrugHistory> table, int ID)
		{
			return table.FirstOrDefault(t =>
				t.ID == ID);
		}
	}
}
